### ISSUE TITLE
[Services] clean URLs? (whitespace, non-breaking-space)

### ISSUE THREAD

**Issue by bobaaaaa** [WeltN24/WeltContentApiClient#42]
Meinungen?

See: https://github.com/WeltN24/funkotron/pull/2031

```
play.api.UnexpectedException: Unexpected exception[URISyntaxException: Illegal character in path at index 54: https://content-api.internal.welt.de/content/113732614 ?show-related=true] at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) at module.common.CustomHttpErrorHandler.onServerError(CustomHttpErrorHandler.scala:49) at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) at scala.util.Try$.apply(Try.scala:192) at scala.util.Failure.recover(Try.scala:216) at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
```

**Comment by thisismana** [comment]
We could also add types to our API, implying that the `articleId` is a Number. This would avoid even some more issues `/content/dickbutt`.
Same goes for the Search endpoint whose typing is not optimal (it also allows Strings for numeric values like the `page` and the `limit`)

Summing it up: 👍
